### ISSUE TITLE
VK_STAMP could be string as well

### ISSUE THREAD

**Issue by ezzyfezzy** [renekorss/Banklink#10]
## Expected Behavior
I can be wrong, but i can't find a reason not to allow string in VK_STAMP (orderId). Ipizza specs do not have type info. It actually works too.

## Actual Behavior
TypeError: Argument 1 passed to Banklink::getPaymentRequest() must be of the type integer, string given

**Very nice code and docs BTW!**

**Comment by renekorss** [comment]
Hi!

Thanks for kind words!

I think you are partially correct. iPizza doesn't seem to have type specified, but for example other supported protocol Estcard requires only int (source: https://www.estcard.ee/doc/ecom.html#_requesting_authorization_form).

This would be breaking change, since we need to change `ProtocolInterface` and all protocol classes. 
Also we should add overriding `getPaymentRequest` method for `Estcard` classes to force `$orderId` to be `int` for it's protocol.

But it seems to be doable. Moved it to 4.0 milestone, since it doesn't seem to be big problem. 
PR is always welcomed. 
I will finally handle this, just probably not in the near future.

**Comment by ezzyfezzy** [comment]
I knew there is a catch :) Simpler solution for me for now is to rewrite my way to use VK_STAMPs. I used string prefixes for different type on payments like "**E**1234" and "**O**12345" and now replaced them with "**100**1234" and "**200**12345".

**Comment by renekorss** [comment]
Nice workaround!

**Comment by renekorss** [comment]
@ezzyfezzy  Are you sure it can be string? Have you tried it on some banks? Using https://github.com/andris9/Pangalink.net, it requires `VK_STAMP` to be number.

**Comment by ezzyfezzy** [comment]
@renekorss I [see](https://github.com/andris9/Pangalink.net/blob/master/lib/banks/ipizza.js#L842). With my own old library i did use alphanumberic values in VK_STAMP field and these worked. [Ipizza specs](https://www.seb.ee/eng/business/everyday-banking/collection-payments/collection-payments-web/bank-link-specification-until) do not specify types or allowed chars.

**Comment by renekorss** [comment]
Closing this as it has workaround and we can't test with Pangalink.net if we allow alphanumeric VK_STAMP.
